{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "UsageError: Line magic function `%` not found.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (1.26.0)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (5.1.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (5.3.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: importlib-metadata<7,>=1.4 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (6.8.0)\n",
      "Requirement already satisfied: numpy<2,>=1.19.3 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (1.24.3)\n",
      "Requirement already satisfied: packaging<24,>=16.8 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from streamlit) (23.1)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (2.1.0)\n",
      "Requirement already satisfied: pillow<10,>=7.1.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (9.5.0)\n",
      "Requirement already satisfied: protobuf<5,>=3.20 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (4.24.2)\n",
      "Requirement already satisfied: pyarrow>=6.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (13.0.0)\n",
      "Requirement already satisfied: pympler<2,>=0.9 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (1.0.1)\n",
      "Requirement already satisfied: python-dateutil<3,>=2.7.3 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from streamlit) (2.8.2)\n",
      "Requirement already satisfied: requests<3,>=2.18 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (2.31.0)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (13.5.2)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (8.2.3)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.1.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (4.5.0)\n",
      "Requirement already satisfied: tzlocal<5,>=1.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (4.3.1)\n",
      "Requirement already satisfied: validators<1,>=0.2 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (0.22.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (3.1.34)\n",
      "Requirement already satisfied: pydeck<1,>=0.8 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from streamlit) (6.3.3)\n",
      "Requirement already satisfied: watchdog>=2.1.5 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from streamlit) (3.0.0)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.2)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.19.0)\n",
      "Requirement already satisfied: toolz in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.10)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from importlib-metadata<7,>=1.4->streamlit) (3.16.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from python-dateutil<3,>=2.7.3->streamlit) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.18->streamlit) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.18->streamlit) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.18->streamlit) (1.26.16)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.18->streamlit) (2023.7.22)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)\n",
      "Requirement already satisfied: pytz-deprecation-shim in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tzlocal<5,>=1.1->streamlit) (0.1.0.post0)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n"
     ]
    }
   ],
   "source": [
    "! pip install --upgrade streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "'pip' is not recognized as an internal or external command,\n",
      "operable program or batch file.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (22.2.1)\n",
      "Collecting pip\n",
      "  Using cached pip-23.2.1-py3-none-any.whl (2.1 MB)\n",
      "Installing collected packages: pip\n",
      "  Attempting uninstall: pip\n",
      "    Found existing installation: pip 22.2.1\n",
      "    Uninstalling pip-22.2.1:\n",
      "      Successfully uninstalled pip-22.2.1\n",
      "Successfully installed pip-23.2.1\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: h5py in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (3.9.0)\n",
      "Requirement already satisfied: numpy>=1.17.3 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from h5py) (1.25.2)\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade h5py "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: numpy in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (1.25.2)\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow\n",
      "  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/ba/7c/b971f2485155917ecdcebb210e021e36a6b65457394590be01cc61515310/tensorflow-2.13.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached tensorflow-2.13.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)\n",
      "Collecting tensorflow-intel==2.13.0 (from tensorflow)\n",
      "  Obtaining dependency information for tensorflow-intel==2.13.0 from https://files.pythonhosted.org/packages/40/fa/98115f6fe4d92e1962f549917be2dc8e369853b7e404191996fedaaf4dd6/tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting absl-py>=1.0.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)\n",
      "Collecting astunparse>=1.6.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
      "Requirement already satisfied: flatbuffers>=23.1.21 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.5.26)\n",
      "Collecting gast<=0.4.0,>=0.2.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)\n",
      "Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
      "Requirement already satisfied: h5py>=2.9.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (3.9.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (16.0.6)\n",
      "Collecting numpy<=1.24.3,>=1.22 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)\n",
      "Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)\n",
      "Requirement already satisfied: packaging in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.1)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.24.2)\n",
      "Requirement already satisfied: setuptools in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (63.2.0)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.16.0)\n",
      "Collecting termcolor>=1.1.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)\n",
      "Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.15.0)\n",
      "Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for grpcio<2.0,>=1.24.3 from https://files.pythonhosted.org/packages/b7/80/56048dd2223a075f421dba172074c93d5545a4348e0699eee15120b4f41d/grpcio-1.57.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached grpcio-1.57.0-cp310-cp310-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting tensorboard<2.14,>=2.13 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)\n",
      "Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for tensorflow-estimator<2.14,>=2.13.0 from https://files.pythonhosted.org/packages/72/5c/c318268d96791c6222ad7df1651bbd1b2409139afeb6f468c0f327177016/tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)\n",
      "Collecting keras<2.14,>=2.13.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for keras<2.14,>=2.13.1 from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata\n",
      "  Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp310-cp310-win_amd64.whl (1.5 MB)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.13.0->tensorflow) (0.41.2)\n",
      "Collecting google-auth<3,>=1.6.3 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for google-auth<3,>=1.6.3 from https://files.pythonhosted.org/packages/9c/8d/bff87fc722553a5691d8514da5523c23547f3894189ba03b57592e37bdc2/google_auth-2.22.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.22.0-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)\n",
      "Collecting markdown>=2.6.8 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for markdown>=2.6.8 from https://files.pythonhosted.org/packages/1a/b5/228c1cdcfe138f1a8e01ab1b54284c8b83735476cb22b6ba251656ed13ad/Markdown-3.4.4-py3-none-any.whl.metadata\n",
      "  Using cached Markdown-3.4.4-py3-none-any.whl.metadata (6.9 kB)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.31.0)\n",
      "Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for tensorboard-data-server<0.8.0,>=0.7.0 from https://files.pythonhosted.org/packages/da/61/6e9ff8258422d287eec718872fb71e05324356722ab658c8afda25f51539/tensorboard_data_server-0.7.1-py3-none-any.whl.metadata\n",
      "  Using cached tensorboard_data_server-0.7.1-py3-none-any.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.3.7)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (5.3.1)\n",
      "Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)\n",
      "Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached rsa-4.9-py3-none-any.whl (34 kB)\n",
      "Requirement already satisfied: urllib3<2.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (1.26.16)\n",
      "Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2023.7.22)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.1.3)\n",
      "Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)\n",
      "Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)\n",
      "Using cached tensorflow-2.13.0-cp310-cp310-win_amd64.whl (1.9 kB)\n",
      "Using cached tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl (276.5 MB)\n",
      "Using cached grpcio-1.57.0-cp310-cp310-win_amd64.whl (4.3 MB)\n",
      "Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)\n",
      "Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)\n",
      "Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)\n",
      "Using cached Markdown-3.4.4-py3-none-any.whl (94 kB)\n",
      "Using cached tensorboard_data_server-0.7.1-py3-none-any.whl (2.4 kB)\n",
      "Installing collected packages: typing-extensions, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, pyasn1, oauthlib, numpy, markdown, keras, grpcio, google-pasta, gast, astunparse, absl-py, rsa, requests-oauthlib, pyasn1-modules, opt-einsum, google-auth, google-auth-oauthlib, tensorboard, tensorflow-intel, tensorflow\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing-extensions 4.7.1\n",
      "    Can't uninstall 'typing-extensions'. No files were found to uninstall.\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.25.2\n",
      "    Can't uninstall 'numpy'. No files were found to uninstall.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Error parsing requirements for typing-extensions: [Errno 2] No such file or directory: 'c:\\\\users\\\\user\\\\appdata\\\\local\\\\programs\\\\python\\\\python310\\\\lib\\\\site-packages\\\\typing_extensions-4.7.1.dist-info\\\\METADATA'\n",
      "    WARNING: No metadata found in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages\n",
      "    WARNING: No metadata found in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages\n",
      "  ERROR: Can't roll back numpy; was not uninstalled\n",
      "ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\Lib\\\\site-packages\\\\numpy\\\\random\\\\mtrand.cp310-win_amd64.pyd'\n",
      "Consider using the `--user` option or check the permissions.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow\n",
      "  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/ba/7c/b971f2485155917ecdcebb210e021e36a6b65457394590be01cc61515310/tensorflow-2.13.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Downloading tensorflow-2.13.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)\n",
      "Collecting tensorflow-intel==2.13.0 (from tensorflow)\n",
      "  Obtaining dependency information for tensorflow-intel==2.13.0 from https://files.pythonhosted.org/packages/40/fa/98115f6fe4d92e1962f549917be2dc8e369853b7e404191996fedaaf4dd6/tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Downloading tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting absl-py>=1.0.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)\n",
      "Collecting astunparse>=1.6.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
      "Requirement already satisfied: flatbuffers>=23.1.21 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.5.26)\n",
      "Collecting gast<=0.4.0,>=0.2.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)\n",
      "Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
      "Requirement already satisfied: h5py>=2.9.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (3.9.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (16.0.6)\n",
      "Collecting numpy<=1.24.3,>=1.22 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)\n",
      "Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)\n",
      "Requirement already satisfied: packaging in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.1)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.24.2)\n",
      "Requirement already satisfied: setuptools in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (63.2.0)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.16.0)\n",
      "Collecting termcolor>=1.1.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)\n",
      "Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.15.0)\n",
      "Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for grpcio<2.0,>=1.24.3 from https://files.pythonhosted.org/packages/b7/80/56048dd2223a075f421dba172074c93d5545a4348e0699eee15120b4f41d/grpcio-1.57.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Downloading grpcio-1.57.0-cp310-cp310-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting tensorboard<2.14,>=2.13 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)\n",
      "Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for tensorflow-estimator<2.14,>=2.13.0 from https://files.pythonhosted.org/packages/72/5c/c318268d96791c6222ad7df1651bbd1b2409139afeb6f468c0f327177016/tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata\n",
      "  Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)\n",
      "Collecting keras<2.14,>=2.13.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for keras<2.14,>=2.13.1 from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata\n",
      "  Downloading keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp310-cp310-win_amd64.whl (1.5 MB)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.13.0->tensorflow) (0.41.2)\n",
      "Collecting google-auth<3,>=1.6.3 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for google-auth<3,>=1.6.3 from https://files.pythonhosted.org/packages/9c/8d/bff87fc722553a5691d8514da5523c23547f3894189ba03b57592e37bdc2/google_auth-2.22.0-py2.py3-none-any.whl.metadata\n",
      "  Downloading google_auth-2.22.0-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)\n",
      "Collecting markdown>=2.6.8 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for markdown>=2.6.8 from https://files.pythonhosted.org/packages/1a/b5/228c1cdcfe138f1a8e01ab1b54284c8b83735476cb22b6ba251656ed13ad/Markdown-3.4.4-py3-none-any.whl.metadata\n",
      "  Downloading Markdown-3.4.4-py3-none-any.whl.metadata (6.9 kB)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.31.0)\n",
      "Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for tensorboard-data-server<0.8.0,>=0.7.0 from https://files.pythonhosted.org/packages/da/61/6e9ff8258422d287eec718872fb71e05324356722ab658c8afda25f51539/tensorboard_data_server-0.7.1-py3-none-any.whl.metadata\n",
      "  Downloading tensorboard_data_server-0.7.1-py3-none-any.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.3.7)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (5.3.1)\n",
      "Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)\n",
      "Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached rsa-4.9-py3-none-any.whl (34 kB)\n",
      "Collecting urllib3<2.0 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for urllib3<2.0 from https://files.pythonhosted.org/packages/c5/05/c214b32d21c0b465506f95c4f28ccbcba15022e000b043b72b3df7728471/urllib3-1.26.16-py2.py3-none-any.whl.metadata\n",
      "  Downloading urllib3-1.26.16-py2.py3-none-any.whl.metadata (48 kB)\n",
      "     ---------------------------------------- 0.0/48.4 kB ? eta -:--:--\n",
      "     --------------------------------- ------ 41.0/48.4 kB ? eta -:--:--\n",
      "     --------------------------------- ------ 41.0/48.4 kB ? eta -:--:--\n",
      "     -------------------------------------- 48.4/48.4 kB 489.1 kB/s eta 0:00:00\n",
      "Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2023.7.22)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.1.3)\n",
      "Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)\n",
      "Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)\n",
      "Using cached tensorflow-2.13.0-cp310-cp310-win_amd64.whl (1.9 kB)\n",
      "Using cached tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl (276.5 MB)\n",
      "Using cached grpcio-1.57.0-cp310-cp310-win_amd64.whl (4.3 MB)\n",
      "Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)\n",
      "Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)\n",
      "Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)\n",
      "Using cached Markdown-3.4.4-py3-none-any.whl (94 kB)\n",
      "Using cached tensorboard_data_server-0.7.1-py3-none-any.whl (2.4 kB)\n",
      "Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)\n",
      "Installing collected packages: urllib3, typing-extensions, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, pyasn1, oauthlib, numpy, markdown, keras, grpcio, google-pasta, gast, astunparse, absl-py, rsa, pyasn1-modules, opt-einsum, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow-intel, tensorflow\n",
      "  Attempting uninstall: urllib3\n",
      "    Found existing installation: urllib3 2.0.4\n",
      "    Uninstalling urllib3-2.0.4:\n",
      "      Successfully uninstalled urllib3-2.0.4\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing_extensions 4.7.1\n",
      "    Uninstalling typing_extensions-4.7.1:\n",
      "      Successfully uninstalled typing_extensions-4.7.1\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.25.2\n",
      "    Uninstalling numpy-1.25.2:\n",
      "      Successfully uninstalled numpy-1.25.2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\Lib\\\\site-packages\\\\markdown\\\\preprocessors.py'\n",
      "Consider using the `--user` option or check the permissions.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow\n",
      "  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/ba/7c/b971f2485155917ecdcebb210e021e36a6b65457394590be01cc61515310/tensorflow-2.13.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached tensorflow-2.13.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)\n",
      "Collecting tensorflow-intel==2.13.0 (from tensorflow)\n",
      "  Obtaining dependency information for tensorflow-intel==2.13.0 from https://files.pythonhosted.org/packages/40/fa/98115f6fe4d92e1962f549917be2dc8e369853b7e404191996fedaaf4dd6/tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting absl-py>=1.0.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)\n",
      "Collecting astunparse>=1.6.0 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
      "Requirement already satisfied: flatbuffers>=23.1.21 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.5.26)\n",
      "Collecting gast<=0.4.0,>=0.2.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)\n",
      "Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
      "Requirement already satisfied: h5py>=2.9.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (3.9.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (16.0.6)\n",
      "Collecting numpy<=1.24.3,>=1.22 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)\n",
      "Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)\n",
      "Requirement already satisfied: packaging in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (23.1)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.24.2)\n",
      "Requirement already satisfied: setuptools in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (63.2.0)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.16.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.3.0)\n",
      "Requirement already satisfied: typing-extensions<4.6.0,>=3.6.6 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (4.5.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (1.15.0)\n",
      "Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for grpcio<2.0,>=1.24.3 from https://files.pythonhosted.org/packages/b7/80/56048dd2223a075f421dba172074c93d5545a4348e0699eee15120b4f41d/grpcio-1.57.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached grpcio-1.57.0-cp310-cp310-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting tensorboard<2.14,>=2.13 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)\n",
      "Requirement already satisfied: tensorflow-estimator<2.14,>=2.13.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (2.13.0)\n",
      "Collecting keras<2.14,>=2.13.1 (from tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for keras<2.14,>=2.13.1 from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata\n",
      "  Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.13.0->tensorflow) (0.31.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.13.0->tensorflow) (0.41.2)\n",
      "Collecting google-auth<3,>=1.6.3 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for google-auth<3,>=1.6.3 from https://files.pythonhosted.org/packages/9c/8d/bff87fc722553a5691d8514da5523c23547f3894189ba03b57592e37bdc2/google_auth-2.22.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached google_auth-2.22.0-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)\n",
      "Collecting markdown>=2.6.8 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Obtaining dependency information for markdown>=2.6.8 from https://files.pythonhosted.org/packages/1a/b5/228c1cdcfe138f1a8e01ab1b54284c8b83735476cb22b6ba251656ed13ad/Markdown-3.4.4-py3-none-any.whl.metadata\n",
      "  Using cached Markdown-3.4.4-py3-none-any.whl.metadata (6.9 kB)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.31.0)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.7.1)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.3.7)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (5.3.1)\n",
      "Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)\n",
      "Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached rsa-4.9-py3-none-any.whl (34 kB)\n",
      "Requirement already satisfied: urllib3<2.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (1.26.16)\n",
      "Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow)\n",
      "  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2023.7.22)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (2.1.3)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (0.5.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.0->tensorflow) (3.2.2)\n",
      "Using cached tensorflow-2.13.0-cp310-cp310-win_amd64.whl (1.9 kB)\n",
      "Using cached tensorflow_intel-2.13.0-cp310-cp310-win_amd64.whl (276.5 MB)\n",
      "Using cached grpcio-1.57.0-cp310-cp310-win_amd64.whl (4.3 MB)\n",
      "Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)\n",
      "Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)\n",
      "Using cached Markdown-3.4.4-py3-none-any.whl (94 kB)\n",
      "Installing collected packages: rsa, pyasn1-modules, numpy, markdown, keras, grpcio, google-pasta, gast, astunparse, absl-py, requests-oauthlib, opt-einsum, google-auth, google-auth-oauthlib, tensorboard, tensorflow-intel, tensorflow\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.25.2\n",
      "    Can't uninstall 'numpy'. No files were found to uninstall.\n",
      "Successfully installed absl-py-1.4.0 astunparse-1.6.3 gast-0.4.0 google-auth-2.22.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.57.0 keras-2.13.1 markdown-3.4.4 numpy-1.24.3 opt-einsum-3.3.0 pyasn1-modules-0.3.0 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.13.0 tensorflow-2.13.0 tensorflow-intel-2.13.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Error parsing requirements for numpy: [Errno 2] No such file or directory: 'c:\\\\users\\\\user\\\\appdata\\\\local\\\\programs\\\\python\\\\python310\\\\lib\\\\site-packages\\\\numpy-1.25.2.dist-info\\\\METADATA'\n",
      "    WARNING: No metadata found in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages\n"
     ]
    }
   ],
   "source": [
    "%pip install --upgrade tensorflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (2.1.0)\n",
      "Requirement already satisfied: numpy>=1.22.4 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from pandas) (1.25.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from pandas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from pandas) (2023.3.post1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in c:\\users\\user\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from pandas) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\user\\appdata\\roaming\\python\\python310\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pyngrokNote: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "  Using cached pyngrok-6.0.0.tar.gz (681 kB)\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Collecting PyYAML (from pyngrok)\n",
      "  Obtaining dependency information for PyYAML from https://files.pythonhosted.org/packages/24/97/9b59b43431f98d01806b288532da38099cc6f2fea0f3d712e21e269c0279/PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)\n",
      "Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)\n",
      "Building wheels for collected packages: pyngrok\n",
      "  Building wheel for pyngrok (setup.py): started\n",
      "  Building wheel for pyngrok (setup.py): finished with status 'done'\n",
      "  Created wheel for pyngrok: filename=pyngrok-6.0.0-py3-none-any.whl size=19898 sha256=cddad9439fbab7d9a809cab8a9b8d12d4f15e12550e45ea042a80c7766e515e2\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\5c\\42\\78\\0c3d438d7f5730451a25f7ac6cbf4391759d22a67576ed7c2c\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Wheel 'pyngrok' located at c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\5c\\42\\78\\0c3d438d7f5730451a25f7ac6cbf4391759d22a67576ed7c2c\\pyngrok-6.0.0-py3-none-any.whl is invalid.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pyngrok\n",
      "  Downloading pyngrok-6.0.0.tar.gz (681 kB)\n",
      "     ---------------------------------------- 0.0/681.2 kB ? eta -:--:--\n",
      "     - -------------------------------------- 30.7/681.2 kB ? eta -:--:--\n",
      "     - -------------------------------------- 30.7/681.2 kB ? eta -:--:--\n",
      "     ---- -------------------------------- 81.9/681.2 kB 508.4 kB/s eta 0:00:02\n",
      "     ----- ------------------------------ 112.6/681.2 kB 595.3 kB/s eta 0:00:01\n",
      "     ------ ----------------------------- 122.9/681.2 kB 514.3 kB/s eta 0:00:02\n",
      "     --------- -------------------------- 174.1/681.2 kB 615.9 kB/s eta 0:00:01\n",
      "     ------------ ----------------------- 245.8/681.2 kB 718.0 kB/s eta 0:00:01\n",
      "     ------------- ---------------------- 256.0/681.2 kB 682.7 kB/s eta 0:00:01\n",
      "     ---------------- ------------------- 307.2/681.2 kB 731.4 kB/s eta 0:00:01\n",
      "     ----------------- ------------------ 327.7/681.2 kB 724.7 kB/s eta 0:00:01\n",
      "     ------------------- ---------------- 368.6/681.2 kB 739.0 kB/s eta 0:00:01\n",
      "     ---------------------- ------------- 419.8/681.2 kB 727.5 kB/s eta 0:00:01\n",
      "     ------------------------ ----------- 471.0/681.2 kB 775.8 kB/s eta 0:00:01\n",
      "     -------------------------- --------- 501.8/681.2 kB 749.3 kB/s eta 0:00:01\n",
      "     ---------------------------------- - 645.1/681.2 kB 903.1 kB/s eta 0:00:01\n",
      "     -----------------------------------  675.8/681.2 kB 925.7 kB/s eta 0:00:01\n",
      "     ------------------------------------ 681.2/681.2 kB 841.8 kB/s eta 0:00:00\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Collecting PyYAML (from pyngrok)\n",
      "  Obtaining dependency information for PyYAML from https://files.pythonhosted.org/packages/24/97/9b59b43431f98d01806b288532da38099cc6f2fea0f3d712e21e269c0279/PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata\n",
      "  Downloading PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)\n",
      "Downloading PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)\n",
      "   ---------------------------------------- 0.0/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   -------------------------------------- 145.3/145.3 kB 308.4 kB/s eta 0:00:00\n",
      "Building wheels for collected packages: pyngrok\n",
      "  Building wheel for pyngrok (setup.py): started\n",
      "  Building wheel for pyngrok (setup.py): finished with status 'done'\n",
      "  Created wheel for pyngrok: filename=pyngrok-6.0.0-py3-none-any.whl size=19898 sha256=cddad9439fbab7d9a809cab8a9b8d12d4f15e12550e45ea042a80c7766e515e2\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\5c\\42\\78\\0c3d438d7f5730451a25f7ac6cbf4391759d22a67576ed7c2c\n",
      "Successfully built pyngrok\n",
      "Installing collected packages: PyYAML, pyngrok\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\Lib\\\\site-packages\\\\PyYAML-6.0.1.dist-info\\\\RECORD'\n",
      "Consider using the `--user` option or check the permissions.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pyngrok\n",
      "  Downloading pyngrok-6.0.0.tar.gz (681 kB)\n",
      "     ---------------------------------------- 0.0/681.2 kB ? eta -:--:--\n",
      "     - ----------------------------------- 30.7/681.2 kB 435.7 kB/s eta 0:00:02\n",
      "     - ----------------------------------- 30.7/681.2 kB 435.7 kB/s eta 0:00:02\n",
      "     - ----------------------------------- 30.7/681.2 kB 435.7 kB/s eta 0:00:02\n",
      "     ----- ------------------------------- 92.2/681.2 kB 438.1 kB/s eta 0:00:02\n",
      "     ----- ------------------------------ 112.6/681.2 kB 504.4 kB/s eta 0:00:02\n",
      "     --------- -------------------------- 174.1/681.2 kB 583.1 kB/s eta 0:00:01\n",
      "     ------------ ----------------------- 245.8/681.2 kB 718.0 kB/s eta 0:00:01\n",
      "     ------------- ---------------------- 256.0/681.2 kB 655.4 kB/s eta 0:00:01\n",
      "     ----------------- ------------------ 327.7/681.2 kB 752.2 kB/s eta 0:00:01\n",
      "     ----------------- ------------------ 337.9/681.2 kB 776.5 kB/s eta 0:00:01\n",
      "     ------------------------- ---------- 491.5/681.2 kB 934.5 kB/s eta 0:00:01\n",
      "     ------------------------- ---------- 491.5/681.2 kB 934.5 kB/s eta 0:00:01\n",
      "     --------------------------- -------- 522.2/681.2 kB 885.8 kB/s eta 0:00:01\n",
      "     -------------------------------------  675.8/681.2 kB 1.1 MB/s eta 0:00:01\n",
      "     -------------------------------------  675.8/681.2 kB 1.1 MB/s eta 0:00:01\n",
      "     ------------------------------------ 681.2/681.2 kB 933.1 kB/s eta 0:00:00\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Collecting PyYAML (from pyngrok)\n",
      "  Obtaining dependency information for PyYAML from https://files.pythonhosted.org/packages/24/97/9b59b43431f98d01806b288532da38099cc6f2fea0f3d712e21e269c0279/PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata\n",
      "  Downloading PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)\n",
      "Downloading PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)\n",
      "   ---------------------------------------- 0.0/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   ---------------------------------------  143.4/145.3 kB ? eta -:--:--\n",
      "   -------------------------------------- 145.3/145.3 kB 785.5 kB/s eta 0:00:00\n",
      "Building wheels for collected packages: pyngrok\n",
      "  Building wheel for pyngrok (setup.py): started\n",
      "  Building wheel for pyngrok (setup.py): finished with status 'done'\n",
      "  Created wheel for pyngrok: filename=pyngrok-6.0.0-py3-none-any.whl size=19898 sha256=cddad9439fbab7d9a809cab8a9b8d12d4f15e12550e45ea042a80c7766e515e2\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\5c\\42\\78\\0c3d438d7f5730451a25f7ac6cbf4391759d22a67576ed7c2c\n",
      "Successfully built pyngrok\n",
      "Installing collected packages: PyYAML, pyngrok\n",
      "Successfully installed PyYAML-6.0.1 pyngrok-6.0.0\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade pyngrok\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "UsageError: %%writefile is a cell magic, but the cell body is empty.\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Writing main.py\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "t=2023-09-06T02:06:45+0100 lvl=eror msg=\"heartbeat timeout, terminating session\" obj=tunnels.session obj=csess id=b06a9c6f99cb clientid=a08f38513c07f9b5c92269b76da79fe5\n",
      "t=2023-09-06T02:06:50+0100 lvl=eror msg=\"session closed, starting reconnect loop\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"session closed\"\n",
      "t=2023-09-06T02:06:52+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:06:53+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:06:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:06:56+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:07:00+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:07:08+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:07:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:07:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:08:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:08:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:09:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:09:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:10:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:10:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:11:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:11:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:12:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:12:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:13:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:13:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:14:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:14:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:15:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:15:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:16:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:16:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:17:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:17:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:18:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:18:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:19:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:19:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:20:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:20:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:21:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:21:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:22:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:22:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:23:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:23:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:24:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:24:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:25:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:25:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:26:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:26:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:27:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:27:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:28:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:28:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:29:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:29:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:30:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:30:54+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:31:24+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:32:04+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: i/o timeout\"\n",
      "t=2023-09-06T02:32:34+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:33:04+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:33:34+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:34:04+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:34:34+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:35:04+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:35:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: i/o timeout\"\n",
      "t=2023-09-06T02:36:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:36:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:37:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:37:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:38:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:38:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:39:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:39:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:40:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:40:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:41:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:41:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:42:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:42:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:43:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:43:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:44:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:44:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:45:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:45:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:46:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:46:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:47:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:47:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:48:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:48:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:49:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:49:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:50:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:50:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:51:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:51:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:52:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:52:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:53:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:53:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:54:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:54:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:55:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:55:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:56:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:56:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:57:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:57:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:58:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:58:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:59:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T02:59:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:00:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:00:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:01:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:01:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:02:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:02:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:03:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:03:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:04:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:04:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:05:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:05:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:06:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:06:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:07:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:07:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:08:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:08:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:09:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:09:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:10:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:10:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:11:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:11:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:12:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:12:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:13:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:13:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:14:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:14:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:15:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:15:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:16:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:16:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:17:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:17:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:18:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:18:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:19:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:19:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:20:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:20:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:21:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:21:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:22:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:22:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:23:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:23:45+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:24:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:24:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.12.62.205:443: i/o timeout\"\n",
      "t=2023-09-06T03:25:35+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.12.62.205:443: i/o timeout\"\n",
      "t=2023-09-06T03:26:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.136.132.147:443: i/o timeout\"\n",
      "t=2023-09-06T03:26:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.136.132.147:443: i/o timeout\"\n",
      "t=2023-09-06T03:27:35+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.136.132.147:443: i/o timeout\"\n",
      "t=2023-09-06T03:28:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.136.132.147:443: i/o timeout\"\n",
      "t=2023-09-06T03:28:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.133.228.214:443: i/o timeout\"\n",
      "t=2023-09-06T03:29:35+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.133.228.214:443: i/o timeout\"\n",
      "t=2023-09-06T03:30:15+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: i/o timeout\"\n",
      "t=2023-09-06T03:30:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp 3.20.27.198:443: i/o timeout\"\n",
      "t=2023-09-06T03:31:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:31:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:32:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:32:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:33:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:33:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:34:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:34:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:35:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:35:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:36:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:36:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:37:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:37:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:38:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:38:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:39:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:39:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:40:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:40:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:41:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:41:55+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T03:42:25+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:08:38+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:09:08+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:09:20+0100 lvl=warn msg=\"failed to check for update\" obj=updater err=\"Post \\\"https://update.equinox.io/check\\\": context deadline exceeded\"\n",
      "t=2023-09-06T20:09:38+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:10:08+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:10:38+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:11:34+0100 lvl=eror msg=\"heartbeat timeout, terminating session\" obj=tunnels.session obj=csess id=25de5b4db39c\n",
      "t=2023-09-06T20:11:34+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to send authentication request: session closed\"\n",
      "t=2023-09-06T20:12:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: i/o timeout\"\n",
      "t=2023-09-06T20:12:44+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:13:14+0100 lvl=eror msg=\"failed to reconnect session\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"failed to dial ngrok server with address \\\"tunnel.us.ngrok.com:443\\\": dial tcp: lookup tunnel.us.ngrok.com: no such host\"\n",
      "t=2023-09-06T20:21:45+0100 lvl=eror msg=\"heartbeat timeout, terminating session\" obj=tunnels.session obj=csess id=1ba9080e4946 clientid=a08f38513c07f9b5c92269b76da79fe5\n",
      "t=2023-09-06T20:21:45+0100 lvl=eror msg=\"session closed, starting reconnect loop\" obj=tunnels.session obj=csess id=2b735bec78f0 err=\"session closed\"\n"
     ]
    }
   ],
   "source": [
    "%%writefile main.py\n",
    "#def main():\n",
    "# The credit card fraud detection system web-based Gui code\n",
    "    import streamlit as st\n",
    "    import numpy as np\n",
    "    import tensorflow as tf\n",
    "    import pandas as pd\n",
    "    from keras.models import load_model\n",
    "    import h5py\n",
    "    import os\n",
    "\n",
    "\n",
    "\n",
    "    header = st.container()\n",
    "    dataset = st.container()\n",
    "    visualisations = st.container()\n",
    "    model_training = st.container()\n",
    "\n",
    "    @st.cache_data\n",
    "    def get_data(filename):\n",
    "        data = pd.read_csv(filename)\n",
    "        return data\n",
    "\n",
    "    with header:\n",
    "        st.title('Credit Card Fraud Detection System')\n",
    "        st.text('In my project, I looked into the trends of online fraudulent credit card transactions')\n",
    "\n",
    "\n",
    "    with dataset:\n",
    "        st.header('The Online Credit Card Transactions Dataset')\n",
    "        st.text('I got this dataset from Kaggle. It contains over six million samples and 11 features of online transactions')\n",
    "        st.subheader('The Datasets First Five Rows(The Head)')\n",
    "        online_transactions = get_data(\"C:/Users/User/Documents/Ntel Ola/GUI/transactions.csv\")\n",
    "        st.write(online_transactions.head())\n",
    "\n",
    "\n",
    "    with visualisations:\n",
    "        st.header('visualisation')\n",
    "        st.subheader('The Distribution of the Online Credit Card Transactions')\n",
    "        payment_type = pd.DataFrame(online_transactions['type'].value_counts())\n",
    "        st.bar_chart(payment_type)\n",
    "\n",
    "\n",
    "    with model_training:\n",
    "        st.header('The Collection of Users Input To Predict Fraudulent Transactions Using The Model')\n",
    "        st.text('I used  deep learning autoencoder algorithm (AE) to create the model')\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "        st.text('The list of online credit card transaction types and their corresponding numbers')\n",
    "        st.markdown('CASH_OUT: 1')\n",
    "        st.markdown('PAYMENT: 2')\n",
    "        st.markdown('CASH_IN: 3')\n",
    "        st.markdown('TRANSFER: 4')\n",
    "        st.markdown('DEBIT: 5')\n",
    "\n",
    "        input_feature_1 = st.slider('What transaction are you performing?', min_value=1, max_value=5, step=1, value=1)\n",
    "        input_feature_2 = st.number_input('What amount would you like to input?', min_value=0.0, step=1000.0)\n",
    "        input_feature_3 = st.number_input('What is your current account balance?', min_value=0.0, step=1000.0)\n",
    "        input_feature_4 = st.number_input('What will your account balance be after the transaction?', min_value=0.0, step=1000.0)\n",
    "\n",
    "    model_path = \"C:/Users/User/Documents/Ntel Ola/GUI/autoencoder_output.h5\"\n",
    "    with h5py.File(model_path, 'r') as model_path:\n",
    "        model = tf.keras.models.load_model(model_path)\n",
    "\n",
    "        def preprocess_input(input_data):\n",
    "            return input_data\n",
    "\n",
    "\n",
    "            if st.button('predict'):\n",
    "                user_input = ([[input_feature_1, input_feature_2, input_feature_3, input_feature_4]])\n",
    "                preprocessed_input = preprocess_input(user_input)\n",
    "                prediction = model.predict(preprocessed_input)\n",
    "\n",
    "                threshold = 0.9\n",
    "                if prediction[0][0] > threshold :\n",
    "                    st.write('This transaction is **fraudulent**. ')\n",
    "                else:\n",
    "                    st.write('This transaction is **non fraudulent**. ')\n",
    "\n",
    "            st.write(f'*N.B:* _For Data Scientist threshold = 0.9 and Anomaly score: {prediction[0][0]}_')\n",
    "#if __name__ == \"__main__\":\n",
    "#    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
